## library(riskRegression)
## d <- sampleData(273)
## v <- sampleData(1827)
## f <- CSC(Hist(time,event)~X1+rcs(X8)+rcs(X9)+rcs(X10),data = d)
## x <- Score(list(f),data = v,formula = Hist(time,event)~1,plots = "roc")
## X <- Score(list(f),data = v,formula = Hist(time,event)~1,plots = "roc",split.method = "bootcv",B = 5)
## Y <- Score(list(f),data = v,formula = Hist(time,event)~1,plots = "roc",split.method = "cv2",B = 1)
## Q <- Score(list(f),data = v,formula = Hist(time,event)~1,plots = "roc",split.method = "loob",B = 100)
## plotROC(x)
## plotROC(X,add = TRUE,col = 2)
## plotROC(Y,add = TRUE,col = 3)
## plotROC(Q,add = TRUE,col = 4)
