// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BaselineHazardFast_cpp
List BaselineHazardFast_cpp(const IntegerVector& status, const NumericVector& pattimes, const NumericVector& Xb, int n_patients, const NumericVector& eventtimes, int cause);
RcppExport SEXP riskRegression_BaselineHazardFast_cpp(SEXP statusSEXP, SEXP pattimesSEXP, SEXP XbSEXP, SEXP n_patientsSEXP, SEXP eventtimesSEXP, SEXP causeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerVector& >::type status(statusSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pattimes(pattimesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type Xb(XbSEXP);
    Rcpp::traits::input_parameter< int >::type n_patients(n_patientsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type eventtimes(eventtimesSEXP);
    Rcpp::traits::input_parameter< int >::type cause(causeSEXP);
    __result = Rcpp::wrap(BaselineHazardFast_cpp(status, pattimes, Xb, n_patients, eventtimes, cause));
    return __result;
END_RCPP
}
