# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
BaselineHazardFast_cpp <- function(status, pattimes, Xb, n_patients, eventtimes, cause) {
    .Call('riskRegression_BaselineHazardFast_cpp', PACKAGE = 'riskRegression', status, pattimes, Xb, n_patients, eventtimes, cause)
}

